"""Make notion expires_at nullable

Revision ID: 264a8f02a756
Revises: 1205f175eda0
Create Date: 2026-06-30 15:30:56.660236

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '264a8f02a756'
down_revision = '1205f175eda0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notion_connections', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('backup_codes')
        batch_op.drop_column('two_factor_enabled')
        batch_op.drop_column('two_factor_secret')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('two_factor_secret', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('two_factor_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('backup_codes', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))

    with op.batch_alter_table('notion_connections', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)

    # ### end Alembic commands ###
