"""Initial schema

Revision ID: 903507473770
Revises: 
Create Date: 2026-06-26 10:37:08.992889

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '903507473770'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('failed_logins', sa.Integer(), nullable=True),
    sa.Column('two_factor_secret', sa.String(), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=True),
    sa.Column('backup_codes', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("email ~ '^[a-zA-Z0-9._%%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$'", name='valid_email'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('field_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notion_db_id', sa.String(), nullable=False),
    sa.Column('title_field', sa.String(), nullable=False),
    sa.Column('due_date_field', sa.String(), nullable=True),
    sa.Column('duration_field', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'notion_db_id', name='unique_user_db_mapping')
    )
    with op.batch_alter_table('field_mappings', schema=None) as batch_op:
        batch_op.create_index('idx_field_mapping_user_id', ['user_id'], unique=False)

    op.create_table('icloud_calendar_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('calendar_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'is_default', name='unique_user_default')
    )
    with op.batch_alter_table('icloud_calendar_selections', schema=None) as batch_op:
        batch_op.create_index('idx_calendar_user_id', ['user_id'], unique=False)

    op.create_table('icloud_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_app_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('icloud_connections', schema=None) as batch_op:
        batch_op.create_index('idx_icloud_user_id', ['user_id'], unique=False)

    op.create_table('notion_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('notion_connections', schema=None) as batch_op:
        batch_op.create_index('idx_notion_user_id', ['user_id'], unique=False)

    op.create_table('notion_feedback_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notion_db_id', sa.String(), nullable=False),
    sa.Column('notion_field', sa.String(), nullable=False),
    sa.Column('corrected_concept', sa.String(), nullable=False),
    sa.Column('feedback_text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('task_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notion_db_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('issues', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('alternatives', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('page_id', sa.String(), nullable=True),
    sa.Column('source_block_ids', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_candidates', schema=None) as batch_op:
        batch_op.create_index('idx_task_candidate_notion_db_id', ['notion_db_id'], unique=False)
        batch_op.create_index('idx_task_candidate_user_id', ['user_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notion_db_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('urgency', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index('idx_task_notion_db_id', ['notion_db_id'], unique=False)
        batch_op.create_index('idx_task_user_id', ['user_id'], unique=False)

    op.create_table('user_ai_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('use_llm_mapping', sa.Boolean(), nullable=True),
    sa.Column('use_learned_detector', sa.Boolean(), nullable=True),
    sa.Column('use_spacy_heuristics', sa.Boolean(), nullable=True),
    sa.Column('use_embedding_similarity', sa.Boolean(), nullable=True),
    sa.Column('use_ml_prioritization', sa.Boolean(), nullable=True),
    sa.Column('use_nlp_urgency', sa.Boolean(), nullable=True),
    sa.Column('use_rl_optimization', sa.Boolean(), nullable=True),
    sa.Column('urgency_learning_scope', sa.String(), nullable=True),
    sa.Column('duration_learning_scope', sa.String(), nullable=True),
    sa.Column('mapping_learning_scope', sa.String(), nullable=True),
    sa.Column('slot_ranking_learning_scope', sa.String(), nullable=True),
    sa.Column('use_nlp_scoring', sa.Boolean(), nullable=True),
    sa.Column('use_ai_page_extraction', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('user_ai_settings', schema=None) as batch_op:
        batch_op.create_index('idx_ai_settings_user_id', ['user_id'], unique=False)

    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('default_notion_db', sa.String(), nullable=True),
    sa.Column('block_size_minutes', sa.Integer(), nullable=True),
    sa.Column('allow_weekends', sa.Boolean(), nullable=True),
    sa.Column('max_blocks_per_day', sa.Integer(), nullable=True),
    sa.Column('work_hours', sa.Float(), nullable=True),
    sa.Column('time_zone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('block_size_minutes > 0', name='check_block_size_positive'),
    sa.CheckConstraint('max_blocks_per_day > 0', name='check_max_blocks_positive'),
    sa.CheckConstraint('work_hours > 0', name='check_work_hours_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_preferences_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.create_index('idx_user_prefs_user_id', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_preferences_user_id'), ['user_id'], unique=False)

    op.create_table('user_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stripe_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('user_subscriptions', schema=None) as batch_op:
        batch_op.create_index('idx_subscription_user_id', ['user_id'], unique=False)

    op.create_table('verification_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('verification_tokens', schema=None) as batch_op:
        batch_op.create_index('ix_verification_token_token_expires_at', ['token', 'expires_at'], unique=False)

    op.create_table('ai_training_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=True),
    sa.Column('label_json', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='fk_ai_event_task_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_ai_event_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_training_events', schema=None) as batch_op:
        batch_op.create_index('idx_ai_event_event_type', ['event_type'], unique=False)
        batch_op.create_index('idx_ai_event_task_id', ['task_id'], unique=False)
        batch_op.create_index('idx_ai_event_user_id', ['user_id'], unique=False)

    op.create_table('task_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_completions', schema=None) as batch_op:
        batch_op.create_index('idx_task_completion_task_id', ['task_id'], unique=False)

    op.create_table('time_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('calendar_id', sa.String(), nullable=False),
    sa.Column('start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('time_blocks', schema=None) as batch_op:
        batch_op.create_index('idx_time_block_calendar_id', ['calendar_id'], unique=False)
        batch_op.create_index('idx_time_block_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_blocks', schema=None) as batch_op:
        batch_op.drop_index('idx_time_block_user_id')
        batch_op.drop_index('idx_time_block_calendar_id')

    op.drop_table('time_blocks')
    with op.batch_alter_table('task_completions', schema=None) as batch_op:
        batch_op.drop_index('idx_task_completion_task_id')

    op.drop_table('task_completions')
    with op.batch_alter_table('ai_training_events', schema=None) as batch_op:
        batch_op.drop_index('idx_ai_event_user_id')
        batch_op.drop_index('idx_ai_event_task_id')
        batch_op.drop_index('idx_ai_event_event_type')

    op.drop_table('ai_training_events')
    with op.batch_alter_table('verification_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_verification_token_token_expires_at')

    op.drop_table('verification_tokens')
    with op.batch_alter_table('user_subscriptions', schema=None) as batch_op:
        batch_op.drop_index('idx_subscription_user_id')

    op.drop_table('user_subscriptions')
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_preferences_user_id'))
        batch_op.drop_index('idx_user_prefs_user_id')

    op.drop_table('user_preferences')
    with op.batch_alter_table('user_ai_settings', schema=None) as batch_op:
        batch_op.drop_index('idx_ai_settings_user_id')

    op.drop_table('user_ai_settings')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('idx_task_user_id')
        batch_op.drop_index('idx_task_notion_db_id')

    op.drop_table('tasks')
    with op.batch_alter_table('task_candidates', schema=None) as batch_op:
        batch_op.drop_index('idx_task_candidate_user_id')
        batch_op.drop_index('idx_task_candidate_notion_db_id')

    op.drop_table('task_candidates')
    op.drop_table('password_reset_tokens')
    op.drop_table('notion_feedback_logs')
    with op.batch_alter_table('notion_connections', schema=None) as batch_op:
        batch_op.drop_index('idx_notion_user_id')

    op.drop_table('notion_connections')
    with op.batch_alter_table('icloud_connections', schema=None) as batch_op:
        batch_op.drop_index('idx_icloud_user_id')

    op.drop_table('icloud_connections')
    with op.batch_alter_table('icloud_calendar_selections', schema=None) as batch_op:
        batch_op.drop_index('idx_calendar_user_id')

    op.drop_table('icloud_calendar_selections')
    with op.batch_alter_table('field_mappings', schema=None) as batch_op:
        batch_op.drop_index('idx_field_mapping_user_id')

    op.drop_table('field_mappings')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
